# Generated by Django 2.1.3 on 2018-12-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataController', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='image'),
        ),
    ]
