# Generated by Django 2.1.3 on 2018-12-09 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataController', '0003_auto_20181209_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='DataController.User'),
        ),
    ]
