# Generated by Django 2.1.3 on 2018-12-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataController', '0004_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_key',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
