# Generated by Django 2.1.3 on 2018-12-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataController', '0005_auto_20181225_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_key',
            field=models.CharField(default='', max_length=40),
        ),
    ]
