# Generated by Django 2.1.3 on 2018-12-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataController', '0006_auto_20181230_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_key',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
