# Generated by Django 2.1.3 on 2018-12-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataController', '0007_auto_20181231_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_key',
            field=models.CharField(max_length=40),
        ),
    ]
