# Generated by Django 2.1.3 on 2019-01-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataController', '0009_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
